---

- name: Ensure containerd.io is installed
  yum:
    name:  "{{ containerd_repo_url }}"
    state: present
    disable_gpg_check: yes
  become: yes

- name: Ensure Docker packages are installed
  yum:
    name: "{{ items }}"
    state: present
  vars:
    items:
    - "docker-ce-{{ docker_version }}"
    - "docker-ce-cli-{{ docker_version }}"
  become: yes

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: Include start.yml
  include_tasks: start.yml